name: Bug Report
description: Bug with the frontend? Report it here!
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before smashing the submit button please review the template.
        Also, please also ensure that this is not a duplicate issue :)
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen and any ways to reproduce the behavior.
      placeholder: A clear and concise description of what the ğŸ is.
    validations:
      required: true