name: Bug Report
description: Bug with the frontend? Report it here!
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before smashing the submit button please review the template.
        Also, please also ensure that this is not a duplicate issue :)
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen and any ways to reproduce the behavior.
      placeholder: A clear and concise description of what the üêû is.
    validations:
      required: true
  - type: dropdown
    id: apptype
    attributes:
      label: App Version
      description: What version of Osmosis are you running?
      options:
        - Main App
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Location
      description: Where are you running this from?
      options:
        - iOS
        - Android
        - Desktop
        - Keplr mobile
    validations:
      required: true

  - type: dropdown
    id: browsertype
    attributes:
      label: Browser Type
      description: (Optional) Which browser are you running on?
      options:
        - Google Chrome
        - Brave
        - Microsoft Edge
        - Mozilla Firefox
        - Safari
        - Other (please specify in description)
    validations:
      required: true
